### ISSUE TITLE
mclahe is unknown package

### ISSUE THREAD

**Issue by MMdeB** [fsc-mib/travel#1]
Dear,

I would like to use your algorithm to segment vessels in CT thoraxs. In the travel_v3 script, mclahe is imported. However, I do not know what package this is and I cannot find it on the internet. Could you help me find te right package?

Thank you very much.

**Comment by fsc-mib** [comment]
Hello,

it is this package:

https://github.com/VincentStimper/mclahe

Best,

Michael

 

Von: MMdeB ***@***.***> 
Gesendet: Donnerstag, 19. Mai 2022 15:11
An: fsc-mib/travel ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [fsc-mib/travel] mclahe is unknown package (Issue #1)

 

Dear,

I would like to use your algorithm to segment vessels in CT thoraxs. In the travel_v3 script, mclahe is imported. However, I do not know what package this is and I cannot find it on the internet. Could you help me find te right package?

Thank you very much.

**Comment by MMdeB** [comment]
Thank you
